module.exports = [
  {"name":"Track With No Name","artist":"Forgemasters"},
  {"name":"Dextrous","artist":"Nightmares On Wax"},
  {"name":"LFO (Leeds Warehouse Mix)","artist":"LFO"},
  {"name":"Polygon Window","artist":"The Dice Man"},
  {"name":"Quoth","artist":"Polygon Window"},
  {"name":"Hall Of Mirrors","artist":"B12"},
  {"name":"Substance Abuse","artist":"F.U.S.E., Richie Hawtin"},
  {"name":"We Are Back","artist":"LFO"},
  {"name":"On","artist":"Aphex Twin"},
  {"name":"Bike","artist":"Autechre"},
  {"name":"Symmetry","artist":"Speedy J"},
  {"name":"Smokebelch I","artist":"The Sabres Of Paradise"},
  {"name":"GAK 4","artist":"Gak"},
  {"name":"Tied Up","artist":"LFO"},
  {"name":"#2","artist":"Aphex Twin"},
  {"name":"Freezone","artist":"Richard H. Kirk"},
  {"name":"Azimuth","artist":"Kenny Larkin"},
  {"name":"Icct Hedral","artist":"Aphex Twin"},
  {"name":"Montreal","artist":"Autechre"},
  {"name":"Silicon Valley","artist":"Elecktroids"},
  {"name":"E Coli","artist":"Ultradyne"},
  {"name":"Extract","artist":"Seefeel"},
  {"name":"Still Fighting","artist":"The Sabres Of Paradise"},
  {"name":"To Cure A Weakling Child","artist":"Aphex Twin"},
  {"name":"Clipper","artist":"Autechre"},
  {"name":"Take Me Baby","artist":"Jimi Tenor"},
  {"name":"Cymbelin","artist":"Move D"},
  {"name":"Paroles (Original)","artist":"Mike Ink"},
  {"name":"Infinite Lites (Primitives Mix)","artist":"B12"},
  {"name":"Hub","artist":"Autechre"},
  {"name":"King Of The Beats","artist":"Jake Slazenger"},
  {"name":"Lilith","artist":"Plaid, Björk"},
  {"name":"Come To Daddy (Pappy Mix)","artist":"Aphex Twin"},
  {"name":"Roygbiv","artist":"Boards of Canada"},
  {"name":"Gay Spunk","artist":"Two Lone Swordsmen"},
  {"name":"Windowlicker","artist":"Aphex Twin"},
  {"name":"Maphive 6.1","artist":"Autechre"},
  {"name":"Come On Let's Go","artist":"Broadcast"},
  {"name":"In A Beautiful Place Out In The Country","artist":"Boards of Canada"},
  {"name":"Sparrow","artist":"Mira Calix"},
  {"name":"Avril 14th","artist":"Aphex Twin"},
  {"name":"Point To B","artist":"Prefuse 73"},
  {"name":"My Red Hot Car","artist":"Squarepusher"},
  {"name":"Sunrays","artist":"The Other People Place"},
  {"name":"Eyen","artist":"Plaid, Benet Walsh"},
  {"name":"Sunshine Recorder","artist":"Boards of Canada"},
  {"name":"Electric Deaf","artist":"Sote"},
  {"name":"Know My Name","artist":"Nightmares On Wax"},
  {"name":"Before We Begin","artist":"Broadcast"},
  {"name":"Me and Guiliani Down by the School Yard - A True Story","artist":"!!!"},
  {"name":"One Word Extinguisher","artist":"Prefuse 73"},
  {"name":"Ultravisitor","artist":"Squarepusher"},
  {"name":"Zeal","artist":"Plaid"},
  {"name":"Ipacial Section","artist":"Autechre"},
  {"name":"Multiply","artist":"Jamie Lidell"},
  {"name":"Dayvan Cowboy","artist":"Boards of Canada"},
  {"name":"Take Ecstasy With Me","artist":"!!!"},
  {"name":"Flip Ya Lid","artist":"Nightmares On Wax"},
  {"name":"Corporeal","artist":"Broadcast"},
  {"name":"Herr Bar","artist":"Clark"},
  {"name":"I Wanna Be Your STD","artist":"Jimmy Edgar"},
  {"name":"Knife","artist":"Grizzly Bear"},
  {"name":"Atlas","artist":"Battles"},
  {"name":"Township Funk","artist":"Dj Mujava"},
  {"name":"GNG BNG","artist":"Flying Lotus"},
  {"name":"Vacuum","artist":"Gang Gang Dance"},
  {"name":"Volcan Veins","artist":"Clark"},
  {"name":"ambivalence avenue","artist":"Bibio"},
  {"name":"Joy Fantastic (feat. Olivier Daysoul)","artist":"Hudson Mohawke, Olivier Day Soul"},
  {"name":"Kobwebz","artist":"Gonjasufi"},
  {"name":"known(1)","artist":"Autechre"},
  {"name":"Out In The Streets","artist":"Africa HiTech"},
  {"name":"MmmHmm","artist":"Flying Lotus, Thundercat"},
  {"name":"Surph","artist":"Rustie"},
  {"name":"Timeaway","artist":"Darkstar"},
  {"name":"See Thru To U","artist":"Flying Lotus, Erykah Badu"},
  {"name":"Higher Ground","artist":"TNGHT, Lunice, Hudson Mohawke"},
  {"name":"Made To Stray","artist":"Mount Kimbie"},
  {"name":"Towards infinite shores","artist":"patten"},
  {"name":"Chrome Country","artist":"Oneohtrix Point Never"},
  {"name":"aisatsana [102]","artist":"Aphex Twin"},
  {"name":"Room 302","artist":"Future Brown, Tink"},
  {"name":"Scud Books","artist":"Hudson Mohawke"},
  {"name":"Rewind","artist":"Kelela"},
  {"name":"Nwa Baloyi","artist":"Nozinja"},
  {"name":"Sticky Drama","artist":"Oneohtrix Point Never"},
  {"name":"Ain't it Funny","artist":"Danny Brown"},
  {"name":"Reach For The Dead","artist":"Boards of Canada"},
  {"name":"Town Crier","artist":"Lafawndah"},
  {"name":"feed1","artist":"Autechre"},
  {"name":"Sad Alron","artist":"Mark Pritchard"},
  {"name":"Born Thieves","artist":"GAIKA"},
  {"name":"The Shape Of Trance To Come","artist":"Lorenzo Senni"},
  {"name":"Frontline","artist":"Kelela"},
  {"name":"Fickle Sun (iii) I'm Set Free","artist":"Brian Eno"},
  {"name":"How We Got By","artist":"Mount Kimbie, James Blake"},
  {"name":"T69 collapse","artist":"Aphex Twin"},
  {"name":"Licking An Orchid","artist":"Yves Tumor, James K"},
  {"name":"Love In The Time Of Lexapro","artist":"Oneohtrix Point Never"},
  {"name":"Radian","artist":"Kelly Moran"}
]