module.exports = [
{artist: "Loraine James", name: "Sensual"},
{artist: "Amnesia Scanner", name: "AS Acá feat. Lalita"},
{artist: "Object Blue", name: "Neo Noir"},
{artist: "Stenny", name: "BFRB"},
{artist: "Lee Gamble", name: "Shards"},
{artist: "Coucou Chloe", name: "Doom"},
{artist: "Oli XL", name: "Orchid Itch"},
{artist: "Rui Ho", name: "Vicissitudes"},
{artist: "N/OBE", name: "The Idiot"},
{artist: "Warrego Walles", name: "Unreleased"},
{artist: "Ikonika", name: "Assert"},
{artist: "Iceboy Violet", name: "bed sheets turn to a white dress"},
{artist: "Ruby My Dear", name: "Chewbacca Orgasm"},
{artist: "BASTIENGOAT", name: "I H8 U"},
{artist: "Ziur", name: "It's Complicated"},
{artist: "Sudanim x Rizzla", name: "Pleasure Lock (Syn Blend)"},
{artist: "Lighght", name: "Gettin Jiggy With It"},
{artist: "Nebulo", name: "Rabbits"},
{artist: "MACE", name: "Reborn as a Magnificent Ox with Four-Inch Horns"},
{artist: "Georgie McVicar", name: "Σ-1g-M4 (Mnim Mix)"},
{artist: "1127", name: "RIZEN20"},
{artist: "Aisha Devi", name: "Uupar-Theory (Gabber Modus Operandi Remix)"},
]