module.exports = [
  {"name":"New Rules","artist":"Dua Lipa"},
  {"name":"2 On","artist":"Tinashe ft. SchoolBoy Q"},
  {"name":"Bololo Haha","artist":"MC Bin Laden"},
  {"name":"What’s A Girl to Do","artist":"Fatima Yamaha"},
  {"name":"Si Estuviésemos Juntos","artist":"Bad Bunny"},
  {"name":"PointillisticT","artist":"Lorenzo Senni"},
  {"name":"Operator","artist":"Lapsley (DJ Koze’s Extended Disco Version)"},
  {"name":"I’m God","artist":"Lil B"},
  {"name":"Wrecking Ball","artist":"Miley Cyrus"},
  {"name":"Hard in da Paint","artist":"Waka Flocka Flame"},
  {"name":"Lockdown Party (DJ Sprinkles Crossfaderama)","artist":"The Mole"},
  {"name":"Hive ft. Casey Veggies & Vince Staples","artist":"Earl Sweatshirt"},
  {"name":"R E A L L O V E","artist":"Factory Floor"},
  {"name":"Raw Cuts #3","artist":"Motor City Drum Ensemble"},
  {"name":"OAR003-B","artist":"Oni Ayhun"},
  {"name":"Shut Up","artist":"Stormzy"},
  {"name":"thank u, next","artist":"Ariana Grande"},
  {"name":"Blissing Me","artist":"Björk"},
  {"name":"Inspector Norse","artist":"Todd Terje"},
  {"name":"Opal","artist":"Bicep"},
  {"name":"Flawless (Remix) ft. Nicki Minaj","artist":"Beyoncé"},
  {"name":"Motivation","artist":"Normani"},
  {"name":"Duck Duck Goose","artist":"CupcakKe"},
  {"name":"Close Your Eyes (And Count to Fuck) ft. Zack de la Rocha","artist":"Run the Jewels"},
  {"name":"Truth","artist":"Kamasi Washington"},
  {"name":"Ryderz","artist":"Hudson Mohawke"},
  {"name":"Sworn to Secrecy Part 2","artist":"Helena Hauff"},
  {"name":"All My Love","artist":"Peder Mannerfelt & Hodge"},
  {"name":"Coffee","artist":"Miguel"},
  {"name":"Bathroom Laughter","artist":"Pissed Jeans"},
  {"name":"Samaritans","artist":"IDLES"},
  {"name":"Climax","artist":"Usher"},
  {"name":"Bodak Yellow","artist":"Cardi B"},
  {"name":"Street Fighter Riddim","artist":"D Double E"},
  {"name":"Blue Pedro","artist":"Bullion"},
  {"name":"Guillotine","artist":"Death Grips"},
  {"name":"Mask Off","artist":"Future"},
  {"name":"Higher Ground","artist":"TNGHT"},
  {"name":"Mercy ft. Big Sean, Pusha T, 2 Chainz","artist":"Kanye West"},
  {"name":"Rodent","artist":"Burial"},
  {"name":"Man Don’t Care ft. Giggs","artist":"JME"},
  {"name":"Hackney Parrot","artist":"Tessela"},
  {"name":"Final Credits","artist":"Midland"},
  {"name":"Know Yourself","artist":"Drake"},
  {"name":"Paranoia","artist":"Chance the Rapper"},
  {"name":"Wakin on a Pretty Day","artist":"Kurt Vile"},
  {"name":"Fruit","artist":"Abra"},
  {"name":"Let It Happen","artist":"Tame Impala"},
  {"name":"Can't Do Without You","artist":"Caribou"},
  {"name":"Seasons (Waiting on You)","artist":"Future Islands"},
  {"name":"To the Moon and Back","artist":"Fever Ray"},
  {"name":"Piel","artist":"Arca"},
  {"name":"True Love Waits","artist":"Thom Yorke"},
  {"name":"Dum Surfer","artist":"King Krule"},
  {"name":"Hannah Montana","artist":"Migos"},
  {"name":"Shut Up Kiss Me","artist":"Angel Olsen"},
  {"name":"Danny Glover","artist":"Young Thug"},
  {"name":"Your Best American Girl","artist":"Mitski"},
  {"name":"Peso","artist":"A$AP Rocky"},
  {"name":"Nights","artist":"Frank Ocean"},
  {"name":"Battle for Middle You","artist":"Julio Bashmore"},
  {"name":"Katy on a Mission","artist":"Katy B"},
  {"name":"CMYK","artist":"James Blake"},
  {"name":"iii's Front","artist":"Overmono"},
  {"name":"Trap Queen","artist":"Fetty Wap"},
  {"name":"Touch Absence","artist":"Lanark Artefax"},
  {"name":"Bax","artist":"Mosca"},
  {"name":"Yeah Right ft. Kendrick Lamar","artist":"Vince Staples"},
  {"name":"Don’t Touch My Hair","artist":"Solange"},
  {"name":"Red Sex","artist":"Vessel"},
  {"name":"Ooouuu","artist":"Young M.A"},
  {"name":"New for U","artist":"Andres"},
  {"name":"Bad Girls","artist":"M.I.A."},
  {"name":"Did You See","artist":"J Hus"},
  {"name":"Dance Yrself Clean","artist":"LCD Soundsystem"},
  {"name":"Queen","artist":"Perfume Genius"},
  {"name":"Rewind","artist":"Kelela"},
  {"name":"I Don’t Like ft. Lil Reese","artist":"Chief Keef"},
  {"name":"BTSTU","artist":"Jai Paul"},
  {"name":"Malamente","artist":"Rosalía"},
  {"name":"Ye Ye","artist":"Daphni"},
  {"name":"Drunk In Love ft. JAY-Z","artist":"Beyoncé"},
  {"name":"Sing About Me, I’m Dying of Thirst","artist":"Kendrick Lamar"},
  {"name":"Footcrab","artist":"Addison Groove"},
  {"name":"Husbands","artist":"Savages"},
  {"name":"212","artist":"Azealia Banks"},
  {"name":"Runaway","artist":"Kanye West"},
  {"name":"Dancing on My Own","artist":"Robyn"},
  {"name":"Why They Hide Their Bodies Under My Garage","artist":"Blawan"},
  {"name":"Numbers on the Board","artist":"Pusha T"},
  {"name":"Oblivion","artist":"Grimes"},
  {"name":"Work","artist":"Rihanna"},
  {"name":"Wut","artist":"Girl Unit"},
  {"name":"Pyramids","artist":"Frank Ocean"},
  {"name":"That's Not Me ft. JME","artist":"Skepta"},
  {"name":"Video Games","artist":"Lana Del Rey"},
  {"name":"Theme From Q","artist":"Objekt"},
  {"name":"For David Robert Jones","artist":"William Basinski"},
  {"name":"Yonkers","artist":"Tyler, the Creator"},
  {"name":"Bipp","artist":"SOPHIE"}
]